name: location_sharing_app
description: Real-time location sharing with GPS, UWB, BLE

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4

  # 네트워킹
  dio: ^5.4.3                      # HTTP 클라이언트
  socket_io_client: ^2.0.3+1       # WebSocket (Socket.IO)

  # 지도
  #google_maps_flutter: ^2.6.1      # Google Maps
  flutter_naver_map: ^1.2.2      # Naver Map
  flutter_polyline_points: ^2.0.0  # 경로 폴리라인

  # 위치
  geolocator: ^11.0.0              # GPS
  permission_handler: ^11.3.1      # 권한 요청
  mediasoup_client_flutter: ^0.8.5

  # 로컬 저장소
  flutter_secure_storage: ^9.0.0   # JWT 토큰 보안 저장
  hive_flutter: ^1.1.0             # 로컬 경로 캐시

  # 라우팅
  go_router: ^14.2.0

  # 설정 저장
  shared_preferences: ^2.2.3

  # Firebase / FCM
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^21.0.0

  # 배터리
  battery_plus: ^6.0.1

  # [Task 2] 화면 꺼짐 방지 (OS Background Kill 예방)
  wakelock_plus: ^1.2.8

  # [Task 2] 효과음
  audioplayers: ^6.0.0

  # 유틸
  intl: ^0.19.0
  uuid: ^4.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_background_service: ^5.1.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
