export const EVENTS = {
  // Client -> Server
  JOIN_SESSION: 'session:join',
  LEAVE_SESSION: 'session:leave',
  LOCATION_UPDATE: 'location:update',
  STATUS_UPDATE: 'status:update',
  SOS_TRIGGER: 'sos:trigger',
  ACTION_INTERACT: 'action:interact',
  GAME_START: 'game:start',
  GAME_REQUEST_STATE: 'game:request_state',
  MEDIA_GET_ROUTER_RTP_CAPABILITIES: 'getRouterRtpCapabilities',
  MEDIA_GET_PRODUCERS: 'getProducers',
  MEDIA_CREATE_WEBRTC_TRANSPORT: 'createWebRtcTransport',
  MEDIA_CONNECT_WEBRTC_TRANSPORT: 'connectWebRtcTransport',
  MEDIA_PRODUCE: 'produce',
  MEDIA_CONSUME: 'consume',

  // Server -> Client
  SESSION_JOINED: 'session:joined',
  MEMBER_JOINED: 'member:joined',
  MEMBER_LEFT: 'member:left',
  MEMBER_UPDATED: 'member:updated',
  LOCATION_CHANGED: 'location:changed',
  STATUS_CHANGED: 'status:changed',
  SOS_ALERT: 'sos:alert',
  SESSION_SNAPSHOT: 'session:snapshot',
  KICKED: 'kicked',
  ROLE_CHANGED: 'role_changed',
  ACTION_RESULT: 'action:result',
  MODULE_ERROR: 'module:error',
  PLAYER_ELIMINATED: 'player:eliminated',
  GAME_OVER: 'game:over',
  GAME_STATE_UPDATE: 'game:state_update',
  TAG_ASSIGNED: 'tag:assigned',
  TAG_TRANSFERRED: 'tag:transferred',
  TAG_STATE_UPDATE: 'tag:state_update',
  ROUND_START: 'round:start',
  ROUND_END: 'round:end',
  VOTE_OPEN: 'vote:open',
  VOTE_CAST: 'vote:cast',
  VOTE_RESULT: 'vote:result',
  MEDIA_NEW_PRODUCER: 'media:newProducer',
  MEDIA_PRODUCER_CLOSED: 'media:producerClosed',
  VOICE_SPEAKING: 'voice:speaking',
  ERROR: 'error',

  // Among Us Client -> Server
  GAME_KILL: 'game:kill',
  GAME_REPORT: 'game:report',
  GAME_EMERGENCY: 'game:emergency',
  GAME_VOTE: 'game:vote',
  GAME_MISSION_DONE: 'game:mission_complete',
  GAME_AI_ASK: 'game:ai_ask',
  GAME_TRIGGER_SABOTAGE: 'game:trigger_sabotage',
  GAME_FIX_SABOTAGE: 'game:fix_sabotage',
  CALL_MEETING: 'call_meeting',
  SUBMIT_VOTE: 'submit_vote',

  // Among Us Server -> Client
  GAME_SABOTAGE_ACTIVE: 'game:sabotage_active',
  GAME_SABOTAGE_FIXED: 'game:sabotage_fixed',
  GAME_STARTED: 'game:started',
  GAME_ROLE_ASSIGNED: 'game:role_assigned',
  GAME_KILL_CONFIRMED: 'game:kill_confirmed',
  GAME_BODY_FOUND: 'game:body_found',
  GAME_MEETING_STARTED: 'game:meeting_started',
  GAME_MEETING_TICK: 'game:meeting_tick',
  GAME_VOTING_STARTED: 'game:voting_started',
  GAME_VOTE_SUBMITTED: 'game:vote_submitted',
  GAME_PRE_VOTE_SUBMITTED: 'game:pre_vote_submitted',
  GAME_VOTE_RESULT: 'game:vote_result',
  GAME_MEETING_ENDED: 'game:meeting_ended',
  GAME_AI_MESSAGE: 'game:ai_message',
  GAME_AI_REPLY: 'game:ai_reply',
  GAME_MISSION_PROGRESS: 'game:mission_progress',
  TASK_PROGRESS: 'task_progress',

  // Fantasy Wars — 거점/스킬/던전 — Client -> Server
  FW_CAPTURE_START:  'fw:capture_start',
  FW_CAPTURE_CANCEL: 'fw:capture_cancel',
  FW_USE_SKILL:      'fw:use_skill',
  FW_ATTACK:         'fw:attack',
  FW_REVIVE:         'fw:revive',
  FW_DUNGEON_ENTER:  'fw:dungeon_enter',

  // Fantasy Wars — 대결 — Client -> Server
  FW_DUEL_CHALLENGE: 'fw:duel:challenge',
  FW_DUEL_ACCEPT:    'fw:duel:accept',
  FW_DUEL_REJECT:    'fw:duel:reject',
  FW_DUEL_CANCEL:    'fw:duel:cancel',
  FW_DUEL_SUBMIT:    'fw:duel:submit',

  // Fantasy Wars — 거점/스킬/던전 — Server -> Client
  FW_CAPTURE_STARTED:  'fw:capture_started',
  FW_CAPTURE_PROGRESS: 'fw:capture_progress',
  FW_CAPTURE_COMPLETE: 'fw:capture_complete',
  FW_CAPTURE_CANCELLED:'fw:capture_cancelled',
  FW_PLAYER_SKILL:     'fw:player_skill',
  FW_SKILL_COOLDOWN:   'fw:skill_cooldown',
  FW_SKILL_USED:       'fw:skill_used',
  FW_PLAYER_ATTACKED:  'fw:player_attacked',
  FW_PLAYER_ELIMINATED:'fw:player_eliminated',
  FW_PLAYER_REVIVED:   'fw:player_revived',
  FW_REVIVE_FAILED:    'fw:revive_failed',
  FW_ARTIFACT_TAKEN:   'fw:artifact_taken',
  FW_ARTIFACT_DROPPED: 'fw:artifact_dropped',
  FW_DUNGEON_CLEARED:  'fw:dungeon_cleared',

  // Fantasy Wars — 대결 — Server -> Client
  FW_DUEL_CHALLENGED:  'fw:duel:challenged',
  FW_DUEL_ACCEPTED:    'fw:duel:accepted',
  FW_DUEL_REJECTED:    'fw:duel:rejected',
  FW_DUEL_CANCELLED:   'fw:duel:cancelled',
  FW_DUEL_STARTED:     'fw:duel:started',
  FW_DUEL_RESULT:      'fw:duel:result',
  FW_DUEL_INVALIDATED: 'fw:duel:invalidated',
};
